language: python

python:
  - "3.5"

install:
  - pip install pylint
  - pip install flake8
  - pip install bandit

jobs:
  include:
    - stage: "Validation" # TODO: Add Unfinished code checker and Commit Message Requirer
      name: "Static Analysis"
      script: flake8 * --exclude=README.md, requirements.txt
      script: python -m pylint * --ignore=README.md, requirements.txt
      script: bandit -r * --exclude=README.md
    - stage: "Test"
      # triggers all test*.py scripts in tests
      name: "Unittests"
      script: python -m unittest discover tests
