language: python

python:
  - "3.5"

install:
  - pip install pylint
  - pip install flake8

jobs:
  include:
    - stage: "Validation"
      name: "Linting and Static Analysis"
      script: python -m pylint *
      script: flake8 * --exclude=README.md, requirements.txt
    - stage: "Test"
      # triggers all test*.py scripts in tests
      name: "Unittests"
      script: python -m unittest discover tests
